= SoreFang - Cyber Threat Intelligence

The indicators are related to https://vuldb.com/?doc.cti[VulDB CTI analysis] of the actor known as https://vuldb.com/?actor.sorefang[SoreFang]. The activity monitoring correlates data from social media, forums, chat rooms, and darknet markets. It helps to determine associated actors, activities, intentions, emerging research, and attacks. Our unique predictive model is able to forecast activities and their characteristics.

Live data and more analysis capabilities are available at https://vuldb.com/?actor.sorefang

== IOC - Indicator of Compromise

The indicators of compromise indicate associated network ressources which are known to be part of research and attack activities.

[options="header"]
|========================================
|ID|IP address|Hostname|Confidence
|1|103.216.221.19|-|High
|========================================

== References

The following list contains external sources which discuss the actor and the associated activities.

* https://us-cert.cisa.gov/ncas/analysis-reports/ar20-198a

== License

(c) https://vuldb.com/?doc.changelog[1997-2021] by https://vuldb.com/?doc.about[vuldb.com]. All data on this page is shared under the license https://creativecommons.org/licenses/by-nc-sa/4.0/[CC BY-NC-SA 4.0]. Questions? Check the https://vuldb.com/?doc.faq[FAQ], read the https://vuldb.com/?doc[documentation] or https://vuldb.com/?contact[contact us]!
