= Astro Locker - Cyber Threat Intelligence

The indicators are related to https://vuldb.com/?doc.cti[VulDB CTI analysis] of the actor known as https://vuldb.com/?actor.astro_locker[Astro Locker]. The activity monitoring correlates data from social media, forums, chat rooms, and darknet markets. It helps to determine associated actors, activities, intentions, emerging research, and attacks. Our unique predictive model is able to forecast activities and their characteristics.

Live data and more analysis capabilities are available at https://vuldb.com/?actor.astro_locker

== Countries

These countries are directly (e.g. origin of attacks) or indirectly (e.g. access by proxy) associated with the actor.

. US
. CN

== IOC - Indicator of Compromise

The indicators of compromise indicate associated network ressources which are known to be part of research and attack activities.

[options="header"]
|========================================
|ID|IP address|Hostname|Confidence
|1|45.134.21.8|-|High
|2|46.21.153.135|135.153.21.46.static.swiftway.net|High
|3|139.60.161.68|-|High
|4|185.38.185.87|-|High
|========================================

== IOA - Indicator of Attack

The indicators of attack list the potential fragments used for technical activities like reconnaissance, exploitation, privilege escalation, and exfiltration. This data is unique as it uses our predictive model for actor profiling.

[options="header"]
|========================================
|ID|Class|Indicator|Confidence
|1|File|/htmlcode/html/indexdefault.asp|High
|2|File|ajax_admin_apis.php|High
|3|File|ajax_php_pecl.php|High
|4|File|books.php|Medium
|5|File|category.cfm|Medium
|6|Argument|bookid|Low
|7|Argument|cat|Low
|8|Argument|employee_id|Medium
|9|Argument|line|Low
|10|Argument|phpversion|Medium
|11|...|...|...
|========================================

There are 4 more IOA items available. Please use our online service to access the data.

== References

The following list contains external sources which discuss the actor and the associated activities.

* https://github.com/sophoslabs/IoCs/blob/master/Ransomware-AstroLocker.csv

== License

(c) https://vuldb.com/?doc.changelog[1997-2021] by https://vuldb.com/?doc.about[vuldb.com]. All data on this page is shared under the license https://creativecommons.org/licenses/by-nc-sa/4.0/[CC BY-NC-SA 4.0]. Questions? Check the https://vuldb.com/?doc.faq[FAQ], read the https://vuldb.com/?doc[documentation] or https://vuldb.com/?contact[contact us]!
