= Dust Storm - Cyber Threat Intelligence

The indicators are related to https://vuldb.com/?doc.cti[VulDB CTI analysis] of the actor known as https://vuldb.com/?actor.dust_storm[Dust Storm]. The activity monitoring correlates data from social media, forums, chat rooms, and darknet markets. It helps to determine associated actors, activities, intentions, emerging research, and attacks. Our unique predictive model is able to forecast activities and their characteristics.

Live data and more analysis capabilities are available at https://vuldb.com/?actor.dust_storm

== Campaigns

The following campaigns are known and can be associated with the actor.

- Dust Storm

== Countries

These countries are directly (e.g. origin of attacks) or indirectly (e.g. access by proxy) associated with the actor.

. CN
. US

== IOC - Indicator of Compromise

The indicators of compromise indicate associated network ressources which are known to be part of research and attack activities.

[options="header"]
|========================================
|ID|IP address|Hostname|Confidence
|1|6.9.2.1|-|High
|2|23.238.229.128|-|High
|3|27.255.72.68|-|High
|4|27.255.72.69|-|High
|5|27.255.72.78|-|High
|6|59.120.59.2|59-120-59-2.hinet-ip.hinet.net|High
|7|59.188.13.133|-|High
|8|59.188.13.137|-|High
|9|67.192.225.83|-|High
|10|98.129.119.156|-|High
|11|111.1.1.66|-|High
|12|111.67.199.213|-|High
|13|111.67.199.222|-|High
|14|112.175.69.60|-|High
|15|112.175.69.89|-|High
|16|113.10.139.218|-|High
|17|113.10.168.22|-|High
|18|114.142.147.53|static-ip-53-147-142-114.rev.dyxnet.com|High
|19|116.255.131.152|-|High
|20|118.99.37.87|-|High
|21|...|...|...
|========================================

There are 14 more IOC items available. Please use our online service to access the data.

== TTP - Tactics, Techniques, Procedures

Tactics, techniques, and procedures summarize the suspected ATT&CK techniques used. This data is unique as it uses our predictive model for actor profiling.

[options="header"]
|========================================
|ID|Technique|Access Vector|Confidence
|1|T1110.001|Improper Restriction of Excessive Authentication Attempts|High
|2|T1600|Cryptographic Issues|High
|========================================

== IOA - Indicator of Attack

The indicators of attack list the potential fragments used for technical activities like reconnaissance, exploitation, privilege escalation, and exfiltration. This data is unique as it uses our predictive model for actor profiling.

[options="header"]
|========================================
|ID|Class|Indicator|Confidence
|1|File|clonos.php|Medium
|2|File|ildap.exe|Medium
|3|File|prod.php|Medium
|4|Argument|cat|Low
|========================================

== References

The following list contains external sources which discuss the actor and the associated activities.

* https://www.threatminer.org/report.php?q=Op_Dust_Storm_Report.pdf&y=2016

== License

(c) https://vuldb.com/?doc.changelog[1997-2021] by https://vuldb.com/?doc.about[vuldb.com]. All data on this page is shared under the license https://creativecommons.org/licenses/by-nc-sa/4.0/[CC BY-NC-SA 4.0]. Questions? Check the https://vuldb.com/?doc.faq[FAQ], read the https://vuldb.com/?doc[documentation] or https://vuldb.com/?contact[contact us]!
