= Wild Neutron - Cyber Threat Intelligence

The indicators are related to https://vuldb.com/?doc.cti[VulDB CTI analysis] of the actor known as https://vuldb.com/?actor.wild_neutron[Wild Neutron]. The activity monitoring correlates data from social media, forums, chat rooms, and darknet markets. It helps to determine associated actors, activities, intentions, emerging research, and attacks. Our unique predictive model is able to forecast activities and their characteristics.

Live data and more analysis capabilities are available at https://vuldb.com/?actor.wild_neutron

== Countries

These countries are directly (e.g. origin of attacks) or indirectly (e.g. access by proxy) associated with the actor.

. DE
. US
. NL
. ...

There are 4 more country items available. Please use our online service to access the data.

== IOC - Indicator of Compromise

The indicators of compromise indicate associated network ressources which are known to be part of research and attack activities.

[options="header"]
|========================================
|ID|IP address|Hostname|Confidence
|1|46.183.217.132|skalli.pereformed.com|High
|2|64.187.225.231|64-187-225-231.quickpacket.com|High
|3|66.55.133.89|66-55-133-89.choopa.net|High
|4|185.10.58.181|mta.requiretailor.com.de|High
|5|217.23.6.13|customer.worldstream.nl|High
|========================================

== TTP - Tactics, Techniques, Procedures

Tactics, techniques, and procedures summarize the suspected ATT&CK techniques used. This data is unique as it uses our predictive model for actor profiling.

[options="header"]
|========================================
|ID|Technique|Access Vector|Confidence
|1|T1068|Execution with Unnecessary Privileges|High
|2|T1211|7PK Security Features|High
|========================================

== IOA - Indicator of Attack

The indicators of attack list the potential fragments used for technical activities like reconnaissance, exploitation, privilege escalation, and exfiltration. This data is unique as it uses our predictive model for actor profiling.

[options="header"]
|========================================
|ID|Class|Indicator|Confidence
|1|File|data/gbconfiguration.dat|High
|2|File|games.php|Medium
|3|File|inc/config.php|High
|4|File|webman/imageSelector.cgi|High
|5|File|XeService.exe|High
|6|Library|lib/commons-beanutils-1.8.0.jar|High
|7|Argument|basePath|Medium
|8|Argument|id|Low
|9|Argument|this|Low
|10|Network Port|Port 9251|Medium
|========================================

== References

The following list contains external sources which discuss the actor and the associated activities.

* https://www.threatminer.org/report.php?q=WildNeutron_Economic_espionage.pdf&y=2015

== License

(c) https://vuldb.com/?doc.changelog[1997-2021] by https://vuldb.com/?doc.about[vuldb.com]. All data on this page is shared under the license https://creativecommons.org/licenses/by-nc-sa/4.0/[CC BY-NC-SA 4.0]. Questions? Check the https://vuldb.com/?doc.faq[FAQ], read the https://vuldb.com/?doc[documentation] or https://vuldb.com/?contact[contact us]!
