= Poison Needles - Cyber Threat Intelligence

The indicators are related to https://vuldb.com/?doc.cti[VulDB CTI analysis] of the actor known as https://vuldb.com/?actor.poison_needles[Poison Needles]. The activity monitoring correlates data from social media, forums, chat rooms, and darknet markets. It helps to determine associated actors, activities, intentions, emerging research, and attacks. Our unique predictive model is able to forecast activities and their characteristics.

Live data and more analysis capabilities are available at https://vuldb.com/?actor.poison_needles

== Campaigns

The following campaigns are known and can be associated with the actor.

- Poison Needles

== IOC - Indicator of Compromise

The indicators of compromise indicate associated network ressources which are known to be part of research and attack activities.

[options="header"]
|========================================
|ID|IP address|Hostname|Confidence
|1|188.241.58.68|swimta.net|High
|========================================

== TTP - Tactics, Techniques, Procedures

Tactics, techniques, and procedures summarize the suspected ATT&CK techniques used. This data is unique as it uses our predictive model for actor profiling.

[options="header"]
|========================================
|ID|Technique|Access Vector|Confidence
|1|T1059.007|Cross Site Scripting|High
|2|T1499|Resource Consumption|High
|========================================

== References

The following list contains external sources which discuss the actor and the associated activities.

* https://blogs.360.cn/post/PoisonNeedles_CVE-2018-15982_EN

== License

(c) https://vuldb.com/?doc.changelog[1997-2021] by https://vuldb.com/?doc.about[vuldb.com]. All data on this page is shared under the license https://creativecommons.org/licenses/by-nc-sa/4.0/[CC BY-NC-SA 4.0]. Questions? Check the https://vuldb.com/?doc.faq[FAQ], read the https://vuldb.com/?doc[documentation] or https://vuldb.com/?contact[contact us]!
