= PowerDuke - Cyber Threat Intelligence

The indicators are related to https://vuldb.com/?doc.cti[VulDB CTI analysis] of the actor known as https://vuldb.com/?actor.powerduke[PowerDuke]. The activity monitoring correlates data from social media, forums, chat rooms, and darknet markets. It helps to determine associated actors, activities, intentions, emerging research, and attacks. Our unique predictive model is able to forecast activities and their characteristics.

Live data and more analysis capabilities are available at https://vuldb.com/?actor.powerduke

== Countries

These countries are directly (e.g. origin of attacks) or indirectly (e.g. access by proxy) associated with the actor.

. CN
. BE
. US

== IOC - Indicator of Compromise

The indicators of compromise indicate associated network ressources which are known to be part of research and attack activities.

[options="header"]
|========================================
|ID|IP address|Hostname|Confidence
|1|65.15.88.243|adsl-065-015-088-243.sip.asm.bellsouth.net|High
|2|81.82.196.162|d5152c4a2.static.telenet.be|High
|3|173.243.80.6|-|High
|4|177.10.96.30|177-10-96-30.najatelecom.local|High
|5|185.124.86.121|hosted-by.bilgehosting.com|High
|6|185.132.124.43|server.moxdc.com|High
|========================================

== TTP - Tactics, Techniques, Procedures

Tactics, techniques, and procedures summarize the suspected ATT&CK techniques used. This data is unique as it uses our predictive model for actor profiling.

[options="header"]
|========================================
|ID|Technique|Access Vector|Confidence
|1|T1059.007|Cross Site Scripting|High
|2|T1068|Execution with Unnecessary Privileges|High
|3|T1499|Resource Consumption|High
|========================================

== IOA - Indicator of Attack

The indicators of attack list the potential fragments used for technical activities like reconnaissance, exploitation, privilege escalation, and exfiltration. This data is unique as it uses our predictive model for actor profiling.

[options="header"]
|========================================
|ID|Class|Indicator|Confidence
|1|File|/setup.cgi|Medium
|2|File|Administrator/add_pictures.php|High
|3|Argument|title|Low
|4|Input Value|/../|Low
|5|Network Port|tcp/4321|Medium
|========================================

== References

The following list contains external sources which discuss the actor and the associated activities.

* https://www.threatminer.org/report.php?q=PowerDuke_WidespreadPost-ElectionSpearPhishingCampaignsTargetingThinkTanksandNGOs-VolexityBlog.pdf&y=2016

== License

(c) https://vuldb.com/?doc.changelog[1997-2021] by https://vuldb.com/?doc.about[vuldb.com]. All data on this page is shared under the license https://creativecommons.org/licenses/by-nc-sa/4.0/[CC BY-NC-SA 4.0]. Questions? Check the https://vuldb.com/?doc.faq[FAQ], read the https://vuldb.com/?doc[documentation] or https://vuldb.com/?contact[contact us]!
